### ISSUE TITLE
Processing bugs 

### ISSUE THREAD

**Issue by martinhiero** [bishun945/pyOWT#3]
```
python run_AquaINFRA.py --input '/data/OWT/OWT_Analyse/FRM4SOC2_FICE22_HEREON_Rrs_for_OWT_HYPERSPECTRAL.txt' --input_option 'csv' --sensor 'HYPER' --output '/data/OWT/OWT_Analyse/FRM4SOC2_FICE22_HEREON_Rrs_for_OWT_HYPERSPECTRAL_results.txt' --output_option 2 
Traceback (most recent call last):
  File "/home/hieronym/Schreibtisch/GitHub/pyOWT/run_AquaINFRA.py", line 298, in <module>
    main()
  File "/home/hieronym/Schreibtisch/GitHub/pyOWT/run_AquaINFRA.py", line 288, in main
    run_owt_csv(input_path_to_csv=args.input, input_sensor=args.sensor, output_path=args.output, output_option=args.output_option)
  File "/home/hieronym/Schreibtisch/GitHub/pyOWT/run_AquaINFRA.py", line 45, in run_owt_csv
    band = [int(x) for x in d.columns.tolist()]
  File "/home/hieronym/Schreibtisch/GitHub/pyOWT/run_AquaINFRA.py", line 45, in <listcomp>
    band = [int(x) for x in d.columns.tolist()]
ValueError: invalid literal for int() with base 10: '  310.0000000   312.5000000   315.0000000   317.5000000   320.0000000   322.5000000   325.0000000   327.5000000   330.0000000   332.5000000   335.0000000   337.5000000   340.0000000   342.5000000   3

```

**Comment by bishun945** [comment]
The bug was raised due to different separators used of input csv files. A new function was added to identify three common separators ",", "\t", and "\s+".
